<?php

use App\Models\Subcategory;
use Illuminate\Database\Seeder;

class SubcategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subcategorie = [
        //Legume
        [
            'id'    => 1,
            'name' => 'Vinete',
            'slug' => 'vinete',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 2,
            'name' => 'Ceapa uscata - alba',
            'slug' => 'ceapa-uscata-alba',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 3,
            'name' => 'Ceapa uscata - rosie',
            'slug' => 'ceapa-uscata-rosie',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 4,
            'name' => 'Ceapa verde',
            'slug' => 'ceapa-verde',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 5,
            'name' => 'Telina radacina',
            'slug' => 'telina-radacina',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 6,
            'name' => 'Leustean radacina',
            'slug' => 'leustean-radacina',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 7,
            'name' => 'Patrunjel radacina',
            'slug' => 'patrunjel-radacina',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 8,
            'name' => 'Morcovi',
            'slug' => 'morcovi',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 9,
            'name' => 'Varza alba',
            'slug' => 'varza-alba',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 10,
            'name' => 'Varza rosie',
            'slug' => 'varza-rosie',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 11,
            'name' => 'Rosii',
            'slug' => 'rosii',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 12,
            'name' => 'Ardei capia',
            'slug' => 'ardei-capia',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 13,
            'name' => 'Ardei gras - alb',
            'slug' => 'ardei-gras-alb',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 14,
            'name' => 'Ardei gras - galben',
            'slug' => 'ardei-gras-galben',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 15,
            'name' => 'Ardei gras - rosu',
            'slug' => 'ardei-gras-rosu',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 16,
            'name' => 'Ardei gras - verde',
            'slug' => 'ardei-gras-verde',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 17,
            'name' => 'Hrean',
            'slug' => 'hrean',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 18,
            'name' => 'Gulii',
            'slug' => 'gulii',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 19,
            'name' => 'Conopida',
            'slug' => 'conopida',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 20,
            'name' => 'Praz',
            'slug' => 'praz',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 21,
            'name' => 'Usturoi uscat',
            'slug' => 'usturoi-uscat',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 22,
            'name' => 'Usturoi verde',
            'slug' => 'usturoi-verde',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 23,
            'name' => 'Ridichi',
            'slug' => 'ridichi',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 24,
            'name' => 'Castraveti lungi',
            'slug' => 'castraveti-lungi',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 25,
            'name' => 'Castraveti cornison',
            'slug' => 'castraveti-cornison',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 26,
            'name' => 'Sfecla rosie',
            'slug' => 'sfecla-rosie',
            'category_id' => 1,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        // Fructe
        [
            'id'    => 27,
            'name' => 'Mere',
            'slug' => 'mere',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 28,
            'name' => 'Pere',
            'slug' => 'pere',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 29,
            'name' => 'Cirese',
            'slug' => 'cirese',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 30,
            'name' => 'Visine',
            'slug' => 'visine',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 31,
            'name' => 'Caise',
            'slug' => 'caise',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 32,
            'name' => 'Gutui',
            'slug' => 'gutui',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 33,
            'name' => 'Prune',
            'slug' => 'prune',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 34,
            'name' => 'Capsuni',
            'slug' => 'capsuni',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 35,
            'name' => 'Afine',
            'slug' => 'afine',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 36,
            'name' => 'Zmeura',
            'slug' => 'zmeura',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 37,
            'name' => 'Mure',
            'slug' => 'mure',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 38,
            'name' => 'Agrise',
            'slug' => 'agrise',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
        [
            'id'    => 39,
            'name' => 'Coacaze',
            'slug' => 'coacaze',
            'category_id' => 2,
            'added_by_id' => 1,
            'approved' => 1,
            'approved_by_id' => 1,
        ],
    ];

    Subcategory::insert($subcategorie);
    }
}
